"""PDF renderer for investigation reports using WeasyPrint + Jinja2.

Renders a ``ReportModel`` instance to a PDF byte string via a Jinja2 HTML
template.  If WeasyPrint is not installed or unavailable at runtime the
renderer gracefully falls back to returning the raw HTML as UTF-8 bytes so
that the MVP can still function without a full PDF toolchain.

Requirements: 11.2, 11.3
"""

from __future__ import annotations

from jinja2 import Template

from app.reports.schemas import ReportModel

# ---------------------------------------------------------------------------
# Jinja2 HTML template
# ---------------------------------------------------------------------------

REPORT_HTML_TEMPLATE: str = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Investigation Report — {{ report.report_id }}</title>
  <style>
    body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 11pt; color: #222; margin: 2cm; }
    h1   { font-size: 18pt; color: #1a3a5c; border-bottom: 2px solid #1a3a5c; padding-bottom: 6px; }
    h2   { font-size: 13pt; color: #1a3a5c; margin-top: 20px; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    th, td { border: 1px solid #ccc; padding: 6px 10px; text-align: left; }
    th { background: #e8edf4; font-weight: bold; }
    .badge-low    { background: #d4edda; color: #155724; padding: 2px 8px; border-radius: 4px; }
    .badge-medium { background: #fff3cd; color: #856404; padding: 2px 8px; border-radius: 4px; }
    .badge-high   { background: #f8d7da; color: #721c24; padding: 2px 8px; border-radius: 4px; }
    .action-monitor  { background: #cce5ff; color: #004085; padding: 4px 12px; border-radius: 4px; font-weight: bold; }
    .action-disclose { background: #fff3cd; color: #856404; padding: 4px 12px; border-radius: 4px; font-weight: bold; }
    .action-freeze   { background: #f8d7da; color: #721c24; padding: 4px 12px; border-radius: 4px; font-weight: bold; }
    .hash-box { font-family: monospace; font-size: 9pt; word-break: break-all;
                background: #f4f4f4; padding: 6px; border: 1px solid #ddd; }
    .section { margin-top: 24px; }
    footer { margin-top: 40px; font-size: 9pt; color: #888; border-top: 1px solid #ccc; padding-top: 8px; }
  </style>
</head>
<body>

  <!-- ------------------------------------------------------------------ -->
  <!-- Header                                                               -->
  <!-- ------------------------------------------------------------------ -->
  <h1>Blockchain Intelligence &amp; VASP Attribution Engine</h1>
  <p>
    <strong>Report ID:</strong> {{ report.report_id }}<br/>
    <strong>Generated At:</strong> {{ report.generated_at.isoformat() }}<br/>
    <strong>Generated By:</strong> {{ report.generated_by }}
  </p>

  <!-- ------------------------------------------------------------------ -->
  <!-- 1. Case Metadata                                                     -->
  <!-- ------------------------------------------------------------------ -->
  <div class="section">
    <h2>1. Case Metadata</h2>
    <table>
      <tr><th>Case ID</th><td>{{ report.case_metadata.case_id }}</td></tr>
      <tr><th>Title</th><td>{{ report.case_metadata.title }}</td></tr>
      <tr><th>Status</th><td>{{ report.case_metadata.status }}</td></tr>
    </table>
  </div>

  <!-- ------------------------------------------------------------------ -->
  <!-- 2. Wallets Analysed                                                  -->
  <!-- ------------------------------------------------------------------ -->
  <div class="section">
    <h2>2. Wallets Analysed</h2>
    {% if report.wallets %}
    <table>
      <thead><tr><th>#</th><th>Address</th><th>Chain</th></tr></thead>
      <tbody>
        {% for w in report.wallets %}
        <tr>
          <td>{{ loop.index }}</td>
          <td style="font-family:monospace;font-size:9pt;">{{ w.address }}</td>
          <td>{{ w.chain }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p><em>No wallets recorded.</em></p>
    {% endif %}
    <p><strong>Chains Analysed:</strong> {{ report.chains_analyzed | join(", ") or "—" }}</p>
  </div>

  <!-- ------------------------------------------------------------------ -->
  <!-- 3. Trace Summary                                                     -->
  <!-- ------------------------------------------------------------------ -->
  <div class="section">
    <h2>3. Trace Summary</h2>
    <table>
      <tr><th>Total Hops</th><td>{{ report.trace_summary.total_hops }}</td></tr>
      <tr><th>Unique Addresses</th><td>{{ report.trace_summary.total_addresses }}</td></tr>
      <tr><th>Total Transactions</th><td>{{ report.trace_summary.total_transactions }}</td></tr>
    </table>
  </div>

  <!-- ------------------------------------------------------------------ -->
  <!-- 4. Attributed VASPs                                                  -->
  <!-- ------------------------------------------------------------------ -->
  <div class="section">
    <h2>4. Attributed VASPs</h2>
    {% if report.attributed_vasps %}
    <table>
      <thead>
        <tr>
          <th>VASP Name</th>
          <th>Category</th>
          <th>Confidence Score</th>
          <th>Low Confidence?</th>
        </tr>
      </thead>
      <tbody>
        {% for v in report.attributed_vasps %}
        <tr>
          <td>{{ v.vasp_name }}</td>
          <td>{{ v.vasp_category }}</td>
          <td>{{ "%.2f"|format(v.confidence_score) }}%</td>
          <td>{{ "Yes" if v.low_confidence else "No" }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p><em>No VASP attributions found.</em></p>
    {% endif %}

    {% if report.low_confidence_attributions %}
    <h3>Low-Confidence Attributions</h3>
    <table>
      <thead><tr><th>VASP Name</th><th>Confidence Score</th></tr></thead>
      <tbody>
        {% for lc in report.low_confidence_attributions %}
        <tr>
          <td>{{ lc.vasp_name }}</td>
          <td>{{ "%.2f"|format(lc.confidence_score) }}%</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endif %}
  </div>

  <!-- ------------------------------------------------------------------ -->
  <!-- 5. Risk Assessment                                                   -->
  <!-- ------------------------------------------------------------------ -->
  <div class="section">
    <h2>5. Risk Assessment</h2>
    <p>
      <strong>Score:</strong> {{ report.risk_assessment.score }} / 100 &nbsp;
      <span class="badge-{{ report.risk_assessment.band }}">
        {{ report.risk_assessment.band | upper }}
      </span>
    </p>
  </div>

  <!-- ------------------------------------------------------------------ -->
  <!-- 6. Typology Findings                                                 -->
  <!-- ------------------------------------------------------------------ -->
  <div class="section">
    <h2>6. Typology Findings</h2>
    {% if report.typologies %}
    <table>
      <thead><tr><th>Typology</th><th>Match Confidence</th></tr></thead>
      <tbody>
        {% for t in report.typologies %}
        <tr>
          <td>{{ t.typology }}</td>
          <td>{{ "%.2f"|format(t.match_confidence * 100) }}%</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p><em>No typology patterns detected.</em></p>
    {% endif %}
  </div>

  <!-- ------------------------------------------------------------------ -->
  <!-- 7. Fund-Flow Timeline                                                -->
  <!-- ------------------------------------------------------------------ -->
  <div class="section">
    <h2>7. Fund-Flow Timeline</h2>
    {% if report.fund_flow_timeline %}
    <table>
      <thead>
        <tr>
          <th>Timestamp</th>
          <th>From</th>
          <th>To</th>
          <th>Amount</th>
          <th>Chain</th>
        </tr>
      </thead>
      <tbody>
        {% for e in report.fund_flow_timeline %}
        <tr>
          <td>{{ e.timestamp.isoformat() }}</td>
          <td style="font-family:monospace;font-size:9pt;">{{ e.from_address }}</td>
          <td style="font-family:monospace;font-size:9pt;">{{ e.to_address }}</td>
          <td>{{ e.amount }}</td>
          <td>{{ e.chain }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p><em>No timeline events recorded.</em></p>
    {% endif %}
  </div>

  <!-- ------------------------------------------------------------------ -->
  <!-- 8. Recommended Action                                                -->
  <!-- ------------------------------------------------------------------ -->
  <div class="section">
    <h2>8. Recommended Action</h2>
    <p>
      <span class="action-{{ report.recommended_action }}">
        {{ report.recommended_action | upper }}
      </span>
    </p>
  </div>

  <!-- ------------------------------------------------------------------ -->
  <!-- 9. Content Hash &amp; Integrity                                      -->
  <!-- ------------------------------------------------------------------ -->
  <div class="section">
    <h2>9. Content Hash (SHA-256)</h2>
    <div class="hash-box">{{ report.content_hash or "(not yet computed)" }}</div>
  </div>

  <!-- ------------------------------------------------------------------ -->
  <!-- 10. Supervisor Signature                                             -->
  <!-- ------------------------------------------------------------------ -->
  <div class="section">
    <h2>10. Supervisor Signature</h2>
    {% if report.supervisor_signature %}
    <div class="hash-box">{{ report.supervisor_signature }}</div>
    {% else %}
    <p><em>This report has not yet been approved by a supervisor.</em></p>
    {% endif %}
  </div>

  <!-- ------------------------------------------------------------------ -->
  <!-- Footer                                                               -->
  <!-- ------------------------------------------------------------------ -->
  <footer>
    <p>
      Generated by the Blockchain Intelligence &amp; VASP Attribution Engine &mdash;
      Report {{ report.report_id }} &mdash; {{ report.generated_at.strftime("%Y-%m-%d %H:%M UTC") }}
    </p>
  </footer>

</body>
</html>
"""


# ---------------------------------------------------------------------------
# PDF renderer
# ---------------------------------------------------------------------------


class WeasyPrintPDFRenderer:
    """Render a ReportModel to PDF bytes using WeasyPrint and Jinja2.

    Falls back to returning UTF-8 encoded HTML when WeasyPrint is unavailable
    (e.g., in CI environments or during the MVP without system-level deps).

    Requirements: 11.2, 11.3
    """

    def render(self, report: ReportModel) -> bytes:
        """Render *report* to PDF (or HTML fallback) bytes.

        1. Render the Jinja2 template to an HTML string.
        2. Attempt WeasyPrint ``HTML(string=html).write_pdf()``.
        3. Return raw HTML bytes if WeasyPrint is unavailable.

        Args:
            report: Fully populated ``ReportModel`` instance.

        Returns:
            PDF bytes if WeasyPrint is available, otherwise UTF-8 HTML bytes.
        """
        # Step 1: Render Jinja2 template
        template = Template(REPORT_HTML_TEMPLATE)
        html: str = template.render(report=report)

        # Step 2: Try WeasyPrint
        try:
            from weasyprint import HTML  # type: ignore[import]

            pdf_bytes: bytes = HTML(string=html).write_pdf()
            return pdf_bytes
        except ImportError:
            # WeasyPrint not installed — return HTML as fallback
            return html.encode("utf-8")
        except Exception:  # noqa: BLE001
            # WeasyPrint available but failed (e.g., missing GTK libs on CI)
            return html.encode("utf-8")
